"""initial migration

Revision ID: 638f7ee3fd49
Revises: 
Create Date: 2018-01-04 18:48:49.282575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '638f7ee3fd49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('blogs', sa.Column('content_html', sa.Text(), nullable=True))
    op.drop_column('blogs', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('body', mysql.TEXT(), nullable=True))
    op.drop_column('blogs', 'content_html')
    op.drop_column('blogs', 'content')
    # ### end Alembic commands ###
